# Generated by Django 4.0.3 on 2022-04-08 17:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='hashtags',
            field=models.ManyToManyField(to='main_app.hashtag'),
        ),
        migrations.CreateModel(
            name='Follows',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followed_user_id', models.ManyToManyField(related_name='user_being_followed', to=settings.AUTH_USER_MODEL)),
                ('following_user_id', models.ManyToManyField(related_name='user_who_follows', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
