# Generated by Django 4.0.3 on 2022-04-14 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_remove_post_user_post_profile_alter_post_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hashtag',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
