# Generated by Django 4.0.3 on 2022-04-07 09:55

import django.core.validators
from django.db import migrations, models
import softuni_web_project.tools.validators


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True, validators=[django.core.validators.MinLengthValidator(2), softuni_web_project.tools.validators.validate_only_letters]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True, validators=[django.core.validators.MinLengthValidator(2), softuni_web_project.tools.validators.validate_only_letters]),
        ),
    ]
