# Generated by Django 4.0.3 on 2022-04-08 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_followers_profile_following'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='followers',
            new_name='followed',
        ),
    ]
