# Generated by Django 4.0.3 on 2022-04-08 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_followers_profile_followed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='followed',
            new_name='followers',
        ),
    ]
