# Generated by Django 4.0.3 on 2022-04-08 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_profile_followers_alter_profile_following'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='followers',
        ),
        migrations.AddField(
            model_name='profile',
            name='followers',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='followers_users', related_query_name='followers_users', to='accounts.profile'),
        ),
        migrations.RemoveField(
            model_name='profile',
            name='following',
        ),
        migrations.AddField(
            model_name='profile',
            name='following',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='following_users', related_query_name='following_users', to='accounts.profile'),
        ),
    ]
