# Generated by Django 4.0.3 on 2022-04-08 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_profile_followers_profile_followers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='followers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followers_users', related_query_name='followers_users', to='accounts.profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='following',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='following_users', related_query_name='following_users', to='accounts.profile'),
        ),
    ]
