# Generated by Django 4.0.3 on 2022-04-14 15:23

import django.core.validators
from django.db import migrations, models
import softuni_web_project.tools.validators


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_profile_followers_alter_profile_following'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=30, unique=True, validators=[django.core.validators.MinLengthValidator(3), softuni_web_project.tools.validators.validate_only_letters_digits_underscores_and_dots, softuni_web_project.tools.validators.validate_only_lowercase]),
        ),
    ]
